# Site settings
title: Colin Pollock
email: colin@colinpollock.net
description: ""
baseurl: ""
url: "http://colinpollock.github.io"
github_username:  colinpollock
linkedin_name: pollockcolin
#twitter_username: ""

# Build settings
markdown: kramdown
